spring.application.name=PaymentService

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/salarypayoutsystem?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#stripe
stripe.api.key=YOUR_STRIPE_SECRET_KEY_HERE

# Server Port
server.port=8083
