server.port=8080
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# Default Admin Credentials (Configurable by whoever downloads the project via .env)
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin123}
